site_name: PhosKinTime
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]

nav:
  - Home: index.md
  - Reference: reference.md
  - Changelog: ../CHANGELOG.md
  - Documentation:
      - Main: ../bin/README.md
      - Configuration: ../config/README.md
      - Kinase Optimization: ../kinopt/README.md
      - ODE Models: ../models/README.md
      - Parameter Estimation: ../paramest/README.md
      - Plotting: ../plotting/README.md
      - Sensitivity Analysis: ../sensitivity/README.md
      - Steady State Calculation: ../steady/README.md
      - Transcription Factor Optimization: ../tfopt/README.md
      - Utils: ../utils/README.md