site_name: PhosKinTime
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]

nav:
  - Home: index.md
  - Reference: reference.md
  - Changelog: Documentation/CHANGELOG.md
  - Documentation:
      - Main: Documentation/bin/README.md
      - Configuration: Documentation/config/README.md
      - Kinase Optimization: Documentation/kinopt/README.md
      - ODE Models: Documentation/models/README.md
      - Parameter Estimation: Documentation/paramest/README.md
      - Plotting: Documentation/plotting/README.md
      - Sensitivity Analysis: Documentation/sensitivity/README.md
      - Steady State Calculation: Documentation/steady/README.md
      - Transcription Factor Optimization: Documentation/tfopt/README.md
      - Utils: Documentation/utils/README.md

markdown_extensions:
  - pymdownx.arithmatex:
      inline_syntax: ['$', '$']
      block_syntax: ['$$', '$$']
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js
  - js/katex-setup.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css
