name: Deploy MkDocs to GitHub Pages

on:
  push:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DOCS: ${{ secrets.DEPLOY_DOCS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs pymdown-extensions

      - name: Check deploy condition
        if: env.DEPLOY_DOCS == 'true'
        run: echo "DEPLOY_DOCS is true, continuing with deployment..."

      - name: Deploy to GitHub Pages
        if: env.DEPLOY_DOCS == 'true'
        run: |
          mkdocs gh-deploy --force
